version : '3'

services:
  nginx-web:
    image: nginx:1.23.4
    container_name: nginx-web
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 页面目录
      - /docker/nginx/html:/usr/share/nginx/html
      # 证书映射
      - /docker/nginx/cert:/etc/nginx/cert
      # 配置文件映射
      - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # 日志目录
      - /docker/nginx/log:/var/log/nginx
    privileged: true
    network_mode: "host"

  campus-server:
    image: campus/campus-imaotai:1.0.12
    container_name: campus-imaotai
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SERVER_PORT: 8160
      spring.config.additional-location: /home/campus/conf/application-dev.yml
    volumes:
      - /docker/server/conf:/home/campus/conf
    privileged: true
    network_mode: "host"
